### ISSUE TITLE
JSON policy format JsonExpr micro-index is missing reference to "is"

### ISSUE THREAD

**Issue by ygrignon-sfdc** [cedar-policy/cedar-docs#142]
**What were you trying to do?**
[JsonExpr Index](https://docs.cedarpolicy.com/policies/json-format.html#JsonExpr-objects) should be complete

**What is wrong and why?**
It's missing the reference to the "is" key

**What do we need to do to fix this?**
Add link to [is](https://docs.cedarpolicy.com/policies/json-format.html#JsonExpr-is)

**Comment by kinclay** [comment]
Thanks for pointing this out. This is updated.
