### ISSUE TITLE
[Cedar Doc Issue] No description of `context` or `entities` JSON format in docs

### ISSUE THREAD

**Issue by mwhicks1** [cedar-policy/cedar-docs#31]
**What were you trying to do?** This is a followup from https://github.com/cedar-policy/cedar-docs/issues/30 which indicates an issue with passing in the `context` record to an evaluation request. In debugging the issue, I found no description in the documentation of the expected JSON format for `context` records, nor did I find a description of the entities JSON format. I ended up using the policy playground to debug the issue.

**What is wrong and why?** The documentation is missing a description of a crucial input format.

**What do we need to do to fix this?** Add a section to the documentation describing the format.

**Comment by khieta** [comment]
Resolved by https://github.com/cedar-policy/cedar-docs/commit/584778016e9d007a92f313facea4a756d247e490 (and followup commits).
