### ISSUE TITLE
[Cedar Doc Issue] Schema

### ISSUE THREAD

**Issue by max2me** [cedar-policy/cedar-docs#37]
We could refine a couple of statements on schema format:

> appliesTo
> Specifies a JSON object containing two lists, principalTypes and resourceTypes, which contain the principal and resources entity types, respectively, that can accompany the action in an authorization request.

Context is also a part of appliesTo.

> Each context entry consists of type and attributes objects. The type object is always the type Record. 

With commonTypes now available, context can be of shape of one of common types.

**Comment by bisdavid** [comment]
Thanks for reporting this Max.  On my todo list. :-)

**Comment by kinclay** [comment]
This has been updated.
