### ISSUE TITLE
[Cedar Doc Issue] How do i validate

### ISSUE THREAD

**Issue by apandays** [cedar-policy/cedar-docs#43]
**What were you trying to do?**

I am trying to validate policies against the schema 

**What is wrong and why?**
There is no mention in the user guide on how to do it. Do i need to call an API or do i need to call isAuthorized? 

**What do we need to do to fix this?**
Provide guidance on how to validate, along with what is validated

**Comment by bisdavid** [comment]
Cedar requires you to call the Validate API operation (see https://github.com/cedar-policy/cedar/tree/main/cedar-policy-validator).

Verified Permissions does it automatically for you if you have the feature enabled (https://docs.aws.amazon.com/verifiedpermissions/latest/userguide/policy-validation-mode.html)
