### ISSUE TITLE
Schema grammar does not include description of commonTypes grammar

### ISSUE THREAD

**Issue by max2me** [cedar-policy/cedar-docs#45]
**What were you trying to do?**
Understand schema grammar
https://docs.cedarpolicy.com/schema/schema-grammar.html

**What is wrong and why?**
commonTypes is mentioned in namespace description but is not covered in grammar details

**What do we need to do to fix this?**
Add grammar details for commonTypes

**Comment by john-h-kastner-aws** [comment]
Closing as fixed by #130
