### ISSUE TITLE
Remove `timestamp` examples

### ISSUE THREAD

**Issue by anwarmamat** [cedar-policy/cedar-docs#58]
**What were you trying to do?**
Cedar [docs](https://docs.cedarpolicy.com/policies/syntax-policy.html#term-parc-context) examples used `timestamp`. We should remove the `timestamp` because it is not supported. 

**What is wrong and why?**
Cedar currently does not support timestamp.  The following example does not work with Cedar. 
```
when {
  context.time.now < timestamp("2022-01-01T10:15:00.021-05:00")
}
```

**What do we need to do to fix this?**
Remove the `timestamp` references.

**Comment by mwhicks1** [comment]
Can you just make this change and submit it as a PR?

**Comment by AMZ-brandon** [comment]
Is there any way to compare the time, or should I just remove that example altogether?

**Comment by AMZ-brandon** [comment]
Thanks! Fixed in [PR 59](https://github.com/cedar-policy/cedar-docs/pull/59).
