### ISSUE TITLE
[Cedar Doc Issue] Typo in Basic Cedar Syntax page

### ISSUE THREAD

**Issue by max2me** [cedar-policy/cedar-docs#65]
https://docs.cedarpolicy.com/policies/syntax-policy.html#term-parc-context

Right now:
> Context elements take the following two forms:

Should be:
> Condition elements take the following two forms:

**Comment by AMZ-brandon** [comment]
Thanks Max. Will draft this up.

**Comment by kinclay** [comment]
This was already taken care of.
