### ISSUE TITLE
[Cedar Doc Issue] Add link to sample application in the RBAC with groups guidance 

### ISSUE THREAD

**Issue by apandays** [cedar-policy/cedar-docs#70]
Let's add a link to a blog and sample application that implements RBAC with groups https://docs.cedarpolicy.com/bestpractices/bp-implementing-roles-groups.html

Blog: https://aws.amazon.com/blogs/devops/manage-roles-and-entitlements-with-pbac-using-amazon-verified-permissions/

Sample App: https://github.com/aws-samples/avp-petstore-sample-v2/

**Comment by AMZ-brandon** [comment]
Okay, will draft this up.

**Comment by kinclay** [comment]
These links have been added.
