### ISSUE TITLE
[Cedar Doc Issue] Update Cedar version on docs.cedarpolicy.com

### ISSUE THREAD

**Issue by max2me** [cedar-policy/cedar-docs#79]
**What is wrong and why?**
Currently docs.cedarpolicy.com reports language version 2.3 yet includes features from Cedar 3.0 such as `is` operator.

**What do we need to do to fix this?**
Scrub Cedar version throughout docs.

**Comment by khieta** [comment]
Update: we're trying to do a better jobs of tracking this now on the document history page (https://docs.cedarpolicy.com/other/doc-history.html). Would still be great to have a way to get different versions of the docs though.

**Comment by khieta** [comment]
Actually, I see that @mwhicks1 already opened #85 for the more general solution -- I'll close this issue then since it's been resolved (for now).
