### ISSUE TITLE
[Cedar Doc Issue] Documentation updates for v3.1.0

### ISSUE THREAD

**Issue by khieta** [cedar-policy/cedar-docs#86]
The upcoming release of Cedar v3.1.0 will require updates to the documentation. The biggest change expected is for the introduction of the new schema format from [RFC24](https://github.com/cedar-policy/rfcs/blob/main/text/0024-schema-syntax.md). The "Document History" page will also need to be updated since this version bumps the language version to 3.1.0.

See the full list of changes in 3.1.0 here: https://github.com/cedar-policy/cedar/blob/release/3.1.x/cedar-policy/CHANGELOG.md

**Comment by khieta** [comment]
Tentatively assigning to @shaobo-he-aws

**Comment by shaobo-he-aws** [comment]
TODO: we should also use human-readable schema format for validation docs.

**Comment by mwhicks1** [comment]
It would be great to set our server up so that customers can see older versions of the docs, too, rather than the docs always being the most recent version. Can we do that (now, or in the near future)?

**Comment by khieta** [comment]
Closing this issue as resolved by #87
