### ISSUE TITLE
[Cedar Doc Issue] Examples for Sets and Records in the Human readable Schema Format

### ISSUE THREAD

**Issue by apandays** [cedar-policy/cedar-docs#90]
**What were you trying to do?**
Create sets and records in the  Human readable Schema Format

There are no examples, and it is difficult to parse the text and figure it out.

**Comment by aaronjeline** [comment]
Is this section in the docs not helpful: https://docs.cedarpolicy.com/schema/human-readable-schema.html#schema-entitytypes-shape-record? (Or was it too hard to find?)

**Comment by apandays** [comment]
I could find it for records, but i could not understand how to use it. For example, how do i make an attribute of an entity a record. The example is missing the scaffolding 

For Sets, i count not find it at all

**Comment by khieta** [comment]
Closing this issue as resolved by #92
