### ISSUE TITLE
[Cedar Doc Issue] Broken Link: Schema Grammar

### ISSUE THREAD

**Issue by raupachz** [cedar-policy/cedar-docs#93]
**What were you trying to do?**

Browsing the Cedar Language Guide and clicking on _Schema Grammar_ in the Schema Section in the left side navigation.

**What is wrong and why?**

404 and no idea

**What do we need to do to fix this?**

Fix the link :)

**Comment by aaronjeline** [comment]
That link is superfluous, the content is covered by https://docs.cedarpolicy.com/schema/human-readable-schema-grammar.html. Thanks for catch, removing it :)
