### ISSUE TITLE
[Cedar Doc Issue] Playground is outdated

### ISSUE THREAD

**Issue by sashee** [cedar-policy/cedar-docs#94]
**What were you trying to do?**

I'm trying to use the human-readable schema and the ```in``` operator on the playground at https://www.cedarpolicy.com/en/playground.

**What is wrong and why?**

The playground uses version 2.4.4 and that does not support these features.

**What do we need to do to fix this?**

Update the playground to the current version.

**Comment by kinclay** [comment]
Thanks, @sashee for reporting this. I'm closing this as it's not a docs issue and have reported your concern to the team in charge of the playground.
